name: .NET Build and Release

on:
  push:
    branches:
      - main

env:
  DOTNET_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore ./dotnet-artifact-test.sln

    - name: Build
      run: dotnet build ./dotnet-artifact-test.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./dotnet-artifact-test.sln --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish ./dotnet-artifact-test.sln --configuration Release --no-restore --no-build --output '${{ env.DOTNET_WEBAPP_PACKAGE_PATH }}'

    - name: List contents   # temp
      run: ls -R            # temp

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-artifact
        path: ${{ env.DOTNET_WEBAPP_PACKAGE_PATH }}

    # - name: Upload artifact as new release asset
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: ${{ env.DOTNET_WEBAPP_PACKAGE_PATH }}
    #     asset_name: dotnet-artifact.zip
    #     asset_content_type: application/zip